defaults.url=https://sentry.io
defaults.org=bangkok-pool-league
defaults.project=bangkok-pool-league
# Using SENTRY_AUTH_TOKEN environment variable
auth.token=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
